swagger: '2.0'
info:
  title: Bank Argent transactions API documentation
  description: Contains all available API endpoints for transactions codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1/
schemes:
  - http
paths:
  /accounts:
    get:
      security:
        - Bearer: []
      summary: Get all accounts of the user
      description: Retrieve a list of all accounts of the user
      produces:
        - application/json
      responses:
        '200':
          description: List of all accounts retrieved successfully
          schema:
            $ref: '#/definitions/Accounts'
        '401':
          description: Unauthorized
        '404':
          description: Accounts not found
        '500':
          description: Internal Server Error
  /accounts/{account_id}/transactions:
    get:
      security:
        - Bearer: []
      summary: Get Account Transactions
      description: Retrieve a list of transactions for a specific account
      parameters:
        - in: path
          name: account_id
          required: true
          type: integer
          description: Account ID
        - in: query
          name: month
          required: false
          type: string
          description: Month (YYYY-MM)
          pattern: '^\d{4}-\d{2}$'
      produces:
        - application/json
      responses:
        '200':
          description: List of transactions retrieved successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Account ID or Month format
        '401':
          description: Unauthorized
        '404':
          description: The specified Account ID was not found
        '500':
          description: Internal Server Error
  /accounts/{account_id}/transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      summary: Get a specific transaction
      description: Retrieve a specific transaction
      parameters:
        - in: path
          name: account_id
          required: true
          type: integer
          description: Account ID
        - in: path
          name: transaction_id
          required: true
          type: integer
          description: Transaction ID
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Account ID or Transaction ID
        '401':
          description: Unauthorized
        '404':
          description: The specified Account ID or Transaction ID was not found
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      summary: Update Transaction Category / Note
      description: Update the category / note of a specific transaction
      parameters:
        - in: path
          name: account_id
          required: true
          type: integer
          description: Account ID
        - in: path
          name: transaction_id
          required: true
          type: integer
          description: Transaction ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/TransactionPayload'
          description: Transaction Payload
      produces:
        - application/json
      responses:
        '200':
          description: Transaction category / note updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Account ID or Transaction ID
        '401':
          description: Unauthorized
        '404':
          description: The specified Account ID or Transaction ID was not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Accounts:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            account_id:
              type: integer
            amount:
              type: number
              format: float
            balance:
              type: number
              format: float
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            transaction_id:
              type: integer
            date:
              type: string
              format: date-time
            description:
              type: string
            category:
              type: string
            note:
              type: string
            amount:
              type: number
              format: float
            balance:
              type: number
              format: float
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transaction_id:
            type: integer
          date:
            type: string
            format: date-time
          description:
            type: string
          category:
            type: string
          note:
            type: string
          amount:
            type: number
            format: float
          balance:
            type: number
            format: float
  TransactionPayload:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transaction_id:
            type: integer
          date:
            type: string
            format: date-time
          description:
            type: string
          category:
            type: string
          note:
            type: string
          amount:
            type: number
            format: float
          balance:
            type: number
            format: float
    required:
      - category
      - note
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transaction_id:
            type: integer
          category:
            type: string
          note:
            type: string
